version: "3"
services:
  db:
    container_name: go-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: logbook_mbkm_unpas
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - api-gateway
    restart: always

networks:
  api-gateway:
    driver: bridge